//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Editor/SVRInputControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SVRInputControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SVRInputControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SVRInputControl"",
    ""maps"": [
        {
            ""name"": ""SVRControl"",
            ""id"": ""8b674d19-650b-49a3-976d-5e29ca88bec5"",
            ""actions"": [
                {
                    ""name"": ""LeftControllerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""cc19e7a1-45c1-440f-b98c-e3cbdf322d28"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerRotation"",
                    ""type"": ""Value"",
                    ""id"": ""cb095d09-0030-4276-8ad5-88cbc3f695b6"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerPrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""f871dd5b-e7b3-47ce-9186-48a6e7d97f6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControllerSecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""0321841d-2e64-4612-a257-139f8a09689d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControllerMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""299dbec1-b37b-4602-951d-4ce2d1ad0480"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControllerTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""453218ed-4889-4e4a-b9ff-7b3c3d4bfdf5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerGrip"",
                    ""type"": ""Value"",
                    ""id"": ""7103c559-6b99-4347-8312-7fa7122ce289"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerStick"",
                    ""type"": ""Value"",
                    ""id"": ""059381c3-ce5a-4778-9ece-eb9a0640cf00"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerTrackingState"",
                    ""type"": ""Value"",
                    ""id"": ""c5e69601-0554-4cf6-a9f6-254f04c1edeb"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerGripButton"",
                    ""type"": ""Button"",
                    ""id"": ""47cf6366-a222-4dee-99fa-efea9424669d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControllerTriggerButton"",
                    ""type"": ""Button"",
                    ""id"": ""de03e7f7-cef1-463a-b596-e7650d923ace"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerTrackingState"",
                    ""type"": ""Value"",
                    ""id"": ""a49d74d5-5a34-4a20-b6ce-72ac2cb8687e"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerStick"",
                    ""type"": ""Value"",
                    ""id"": ""e8fb59c5-d460-4a9e-8cb2-8183051fb607"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerGrip"",
                    ""type"": ""Value"",
                    ""id"": ""bdfcc6db-f827-4593-be2a-46746e41a662"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""7bf4dc77-974c-4a94-a17b-fe2b43ba245d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""dcc9da17-82bd-4a9b-aed1-ea746d388fb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerSecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""fcb9d933-2e94-4872-a07a-912234f70467"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerPrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""b4a30d5f-0c09-42d2-9bcd-409656b4956d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerRotation"",
                    ""type"": ""Value"",
                    ""id"": ""185adf72-5845-421d-80ff-91b4947b4cb5"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""205cdda7-92fa-46fa-b3fc-244c8dee4f47"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerGripButton"",
                    ""type"": ""Button"",
                    ""id"": ""6bfe2a2e-d5e7-48ec-8286-d51b617b8042"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerTriggerButton"",
                    ""type"": ""Button"",
                    ""id"": ""42e4143b-5ece-47d3-bf27-54480bed474b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControllerDeviceVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""c77f3af2-011d-4669-ab9a-3f009fdceff2"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerDeviceVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""a216abef-44e6-4406-88c4-412f1a2ef14d"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerPrimary2DAxisClick"",
                    ""type"": ""Button"",
                    ""id"": ""032c1e03-ce5f-4b69-953f-9cd99869ee91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerPrimary2DAxisClick"",
                    ""type"": ""Button"",
                    ""id"": ""5da3a40f-0304-4ece-8f94-15f914e05fe3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControllerDeviceAngularVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""30132975-ac4d-47f0-997e-36b1272c9b69"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerDeviceAngularVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""363ec9cb-dd63-49b8-80b9-b77b990f02d1"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""78dde180-83a7-44e9-886e-0be9292ea61b"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e035d2fa-9742-4435-98cf-3dcaca209870"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a8baedc-abe5-4ed8-9936-427770de6dfe"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerPrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cafb53a-c113-49fb-8da2-927a6043cf21"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerSecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73230344-44f4-4935-b99f-ded5756e20b4"",
                    ""path"": ""<SVRInputDevice>/MenuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94da3d71-ed61-48fe-9233-c812456e33de"",
                    ""path"": ""<XRController>{LeftHand}/{Trigger}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1288088-ee3d-46c5-b98b-7896443f862e"",
                    ""path"": ""<XRController>{LeftHand}/{Grip}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cdcc315-9c63-4355-b2e3-cf5f2475bf32"",
                    ""path"": ""<XRController>{LeftHand}/Primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""442604e5-f1a5-4fec-b7a7-ce27e320627a"",
                    ""path"": ""<XRController>{LeftHand}/trackingState"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerTrackingState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc0f2015-7091-4f18-a249-73796e45fe18"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b214a381-17e5-465b-ac7f-fe8265f28db4"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c18266a-710a-42f1-aac2-0f4fbf090eaf"",
                    ""path"": ""<XRController>{RightHand}/PrimaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerPrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0141bc40-f9bb-495d-be7f-9f6a6ad86103"",
                    ""path"": ""<XRController>{RightHand}/SecondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerSecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f66b35ed-d611-442c-b2fb-8335fbe1d276"",
                    ""path"": ""<XRController>{RightHand}/MenuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b973f67f-bc09-4e65-a931-18eb8775c3e6"",
                    ""path"": ""<XRController>{RightHand}/Trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9dbfaff-c611-4fac-af46-d97b9a512c63"",
                    ""path"": ""<XRController>{RightHand}/Grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04d2cf2e-65a3-4a25-9dd7-206674bb8f40"",
                    ""path"": ""<XRController>{RightHand}/Primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""758a0649-ef45-4fda-aeaf-e60c63915a22"",
                    ""path"": ""<XRController>{RightHand}/trackingState"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerTrackingState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ce21d19-de05-491a-a898-0fcdf3c31550"",
                    ""path"": ""<XRController>{RightHand}/GripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerGripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d21f483-7eb1-4318-af11-14306e28714a"",
                    ""path"": ""<XRController>{RightHand}/TriggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerTriggerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""516f5063-65b5-433c-9c24-50b37a70a3a6"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerGripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5fe8be4-b481-4ea0-ab12-001918b77b7a"",
                    ""path"": ""<XRController>{LeftHand}/TriggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerTriggerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""427708a9-5e33-4138-95f3-89f2c4e333b0"",
                    ""path"": ""<XRController>{LeftHand}/{controllerVelocity}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerDeviceVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51e4a80e-9e1b-47da-babe-465356e82a1c"",
                    ""path"": ""<XRController>{RightHand}/{controllerVelocity}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerDeviceVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c462516-f00e-4927-8c15-834bece831f2"",
                    ""path"": ""<XRController>{LeftHand}/{Primary2DAxisClick}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerPrimary2DAxisClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a255be6-d40c-4354-8b13-ca3e4dd66d80"",
                    ""path"": ""<XRController>{RightHand}/{Primary2DAxisClick}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerPrimary2DAxisClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""481be4a9-3adb-42eb-942e-a37cd1c5a450"",
                    ""path"": ""<XRController>{LeftHand}/{controllerAngularVelocity}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerDeviceAngularVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd9c4c70-2890-4e6c-a2f6-529d7d67963a"",
                    ""path"": ""<XRController>{RightHand}/{controllerAngularVelocity}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerDeviceAngularVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SVRControl
        m_SVRControl = asset.FindActionMap("SVRControl", throwIfNotFound: true);
        m_SVRControl_LeftControllerPosition = m_SVRControl.FindAction("LeftControllerPosition", throwIfNotFound: true);
        m_SVRControl_LeftControllerRotation = m_SVRControl.FindAction("LeftControllerRotation", throwIfNotFound: true);
        m_SVRControl_LeftControllerPrimaryButton = m_SVRControl.FindAction("LeftControllerPrimaryButton", throwIfNotFound: true);
        m_SVRControl_LeftControllerSecondaryButton = m_SVRControl.FindAction("LeftControllerSecondaryButton", throwIfNotFound: true);
        m_SVRControl_LeftControllerMenuButton = m_SVRControl.FindAction("LeftControllerMenuButton", throwIfNotFound: true);
        m_SVRControl_LeftControllerTrigger = m_SVRControl.FindAction("LeftControllerTrigger", throwIfNotFound: true);
        m_SVRControl_LeftControllerGrip = m_SVRControl.FindAction("LeftControllerGrip", throwIfNotFound: true);
        m_SVRControl_LeftControllerStick = m_SVRControl.FindAction("LeftControllerStick", throwIfNotFound: true);
        m_SVRControl_LeftControllerTrackingState = m_SVRControl.FindAction("LeftControllerTrackingState", throwIfNotFound: true);
        m_SVRControl_LeftControllerGripButton = m_SVRControl.FindAction("LeftControllerGripButton", throwIfNotFound: true);
        m_SVRControl_LeftControllerTriggerButton = m_SVRControl.FindAction("LeftControllerTriggerButton", throwIfNotFound: true);
        m_SVRControl_RightControllerTrackingState = m_SVRControl.FindAction("RightControllerTrackingState", throwIfNotFound: true);
        m_SVRControl_RightControllerStick = m_SVRControl.FindAction("RightControllerStick", throwIfNotFound: true);
        m_SVRControl_RightControllerGrip = m_SVRControl.FindAction("RightControllerGrip", throwIfNotFound: true);
        m_SVRControl_RightControllerTrigger = m_SVRControl.FindAction("RightControllerTrigger", throwIfNotFound: true);
        m_SVRControl_RightControllerMenuButton = m_SVRControl.FindAction("RightControllerMenuButton", throwIfNotFound: true);
        m_SVRControl_RightControllerSecondaryButton = m_SVRControl.FindAction("RightControllerSecondaryButton", throwIfNotFound: true);
        m_SVRControl_RightControllerPrimaryButton = m_SVRControl.FindAction("RightControllerPrimaryButton", throwIfNotFound: true);
        m_SVRControl_RightControllerRotation = m_SVRControl.FindAction("RightControllerRotation", throwIfNotFound: true);
        m_SVRControl_RightControllerPosition = m_SVRControl.FindAction("RightControllerPosition", throwIfNotFound: true);
        m_SVRControl_RightControllerGripButton = m_SVRControl.FindAction("RightControllerGripButton", throwIfNotFound: true);
        m_SVRControl_RightControllerTriggerButton = m_SVRControl.FindAction("RightControllerTriggerButton", throwIfNotFound: true);
        m_SVRControl_LeftControllerDeviceVelocity = m_SVRControl.FindAction("LeftControllerDeviceVelocity", throwIfNotFound: true);
        m_SVRControl_RightControllerDeviceVelocity = m_SVRControl.FindAction("RightControllerDeviceVelocity", throwIfNotFound: true);
        m_SVRControl_LeftControllerPrimary2DAxisClick = m_SVRControl.FindAction("LeftControllerPrimary2DAxisClick", throwIfNotFound: true);
        m_SVRControl_RightControllerPrimary2DAxisClick = m_SVRControl.FindAction("RightControllerPrimary2DAxisClick", throwIfNotFound: true);
        m_SVRControl_LeftControllerDeviceAngularVelocity = m_SVRControl.FindAction("LeftControllerDeviceAngularVelocity", throwIfNotFound: true);
        m_SVRControl_RightControllerDeviceAngularVelocity = m_SVRControl.FindAction("RightControllerDeviceAngularVelocity", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SVRControl
    private readonly InputActionMap m_SVRControl;
    private List<ISVRControlActions> m_SVRControlActionsCallbackInterfaces = new List<ISVRControlActions>();
    private readonly InputAction m_SVRControl_LeftControllerPosition;
    private readonly InputAction m_SVRControl_LeftControllerRotation;
    private readonly InputAction m_SVRControl_LeftControllerPrimaryButton;
    private readonly InputAction m_SVRControl_LeftControllerSecondaryButton;
    private readonly InputAction m_SVRControl_LeftControllerMenuButton;
    private readonly InputAction m_SVRControl_LeftControllerTrigger;
    private readonly InputAction m_SVRControl_LeftControllerGrip;
    private readonly InputAction m_SVRControl_LeftControllerStick;
    private readonly InputAction m_SVRControl_LeftControllerTrackingState;
    private readonly InputAction m_SVRControl_LeftControllerGripButton;
    private readonly InputAction m_SVRControl_LeftControllerTriggerButton;
    private readonly InputAction m_SVRControl_RightControllerTrackingState;
    private readonly InputAction m_SVRControl_RightControllerStick;
    private readonly InputAction m_SVRControl_RightControllerGrip;
    private readonly InputAction m_SVRControl_RightControllerTrigger;
    private readonly InputAction m_SVRControl_RightControllerMenuButton;
    private readonly InputAction m_SVRControl_RightControllerSecondaryButton;
    private readonly InputAction m_SVRControl_RightControllerPrimaryButton;
    private readonly InputAction m_SVRControl_RightControllerRotation;
    private readonly InputAction m_SVRControl_RightControllerPosition;
    private readonly InputAction m_SVRControl_RightControllerGripButton;
    private readonly InputAction m_SVRControl_RightControllerTriggerButton;
    private readonly InputAction m_SVRControl_LeftControllerDeviceVelocity;
    private readonly InputAction m_SVRControl_RightControllerDeviceVelocity;
    private readonly InputAction m_SVRControl_LeftControllerPrimary2DAxisClick;
    private readonly InputAction m_SVRControl_RightControllerPrimary2DAxisClick;
    private readonly InputAction m_SVRControl_LeftControllerDeviceAngularVelocity;
    private readonly InputAction m_SVRControl_RightControllerDeviceAngularVelocity;
    public struct SVRControlActions
    {
        private @SVRInputControl m_Wrapper;
        public SVRControlActions(@SVRInputControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftControllerPosition => m_Wrapper.m_SVRControl_LeftControllerPosition;
        public InputAction @LeftControllerRotation => m_Wrapper.m_SVRControl_LeftControllerRotation;
        public InputAction @LeftControllerPrimaryButton => m_Wrapper.m_SVRControl_LeftControllerPrimaryButton;
        public InputAction @LeftControllerSecondaryButton => m_Wrapper.m_SVRControl_LeftControllerSecondaryButton;
        public InputAction @LeftControllerMenuButton => m_Wrapper.m_SVRControl_LeftControllerMenuButton;
        public InputAction @LeftControllerTrigger => m_Wrapper.m_SVRControl_LeftControllerTrigger;
        public InputAction @LeftControllerGrip => m_Wrapper.m_SVRControl_LeftControllerGrip;
        public InputAction @LeftControllerStick => m_Wrapper.m_SVRControl_LeftControllerStick;
        public InputAction @LeftControllerTrackingState => m_Wrapper.m_SVRControl_LeftControllerTrackingState;
        public InputAction @LeftControllerGripButton => m_Wrapper.m_SVRControl_LeftControllerGripButton;
        public InputAction @LeftControllerTriggerButton => m_Wrapper.m_SVRControl_LeftControllerTriggerButton;
        public InputAction @RightControllerTrackingState => m_Wrapper.m_SVRControl_RightControllerTrackingState;
        public InputAction @RightControllerStick => m_Wrapper.m_SVRControl_RightControllerStick;
        public InputAction @RightControllerGrip => m_Wrapper.m_SVRControl_RightControllerGrip;
        public InputAction @RightControllerTrigger => m_Wrapper.m_SVRControl_RightControllerTrigger;
        public InputAction @RightControllerMenuButton => m_Wrapper.m_SVRControl_RightControllerMenuButton;
        public InputAction @RightControllerSecondaryButton => m_Wrapper.m_SVRControl_RightControllerSecondaryButton;
        public InputAction @RightControllerPrimaryButton => m_Wrapper.m_SVRControl_RightControllerPrimaryButton;
        public InputAction @RightControllerRotation => m_Wrapper.m_SVRControl_RightControllerRotation;
        public InputAction @RightControllerPosition => m_Wrapper.m_SVRControl_RightControllerPosition;
        public InputAction @RightControllerGripButton => m_Wrapper.m_SVRControl_RightControllerGripButton;
        public InputAction @RightControllerTriggerButton => m_Wrapper.m_SVRControl_RightControllerTriggerButton;
        public InputAction @LeftControllerDeviceVelocity => m_Wrapper.m_SVRControl_LeftControllerDeviceVelocity;
        public InputAction @RightControllerDeviceVelocity => m_Wrapper.m_SVRControl_RightControllerDeviceVelocity;
        public InputAction @LeftControllerPrimary2DAxisClick => m_Wrapper.m_SVRControl_LeftControllerPrimary2DAxisClick;
        public InputAction @RightControllerPrimary2DAxisClick => m_Wrapper.m_SVRControl_RightControllerPrimary2DAxisClick;
        public InputAction @LeftControllerDeviceAngularVelocity => m_Wrapper.m_SVRControl_LeftControllerDeviceAngularVelocity;
        public InputAction @RightControllerDeviceAngularVelocity => m_Wrapper.m_SVRControl_RightControllerDeviceAngularVelocity;
        public InputActionMap Get() { return m_Wrapper.m_SVRControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SVRControlActions set) { return set.Get(); }
        public void AddCallbacks(ISVRControlActions instance)
        {
            if (instance == null || m_Wrapper.m_SVRControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SVRControlActionsCallbackInterfaces.Add(instance);
            @LeftControllerPosition.started += instance.OnLeftControllerPosition;
            @LeftControllerPosition.performed += instance.OnLeftControllerPosition;
            @LeftControllerPosition.canceled += instance.OnLeftControllerPosition;
            @LeftControllerRotation.started += instance.OnLeftControllerRotation;
            @LeftControllerRotation.performed += instance.OnLeftControllerRotation;
            @LeftControllerRotation.canceled += instance.OnLeftControllerRotation;
            @LeftControllerPrimaryButton.started += instance.OnLeftControllerPrimaryButton;
            @LeftControllerPrimaryButton.performed += instance.OnLeftControllerPrimaryButton;
            @LeftControllerPrimaryButton.canceled += instance.OnLeftControllerPrimaryButton;
            @LeftControllerSecondaryButton.started += instance.OnLeftControllerSecondaryButton;
            @LeftControllerSecondaryButton.performed += instance.OnLeftControllerSecondaryButton;
            @LeftControllerSecondaryButton.canceled += instance.OnLeftControllerSecondaryButton;
            @LeftControllerMenuButton.started += instance.OnLeftControllerMenuButton;
            @LeftControllerMenuButton.performed += instance.OnLeftControllerMenuButton;
            @LeftControllerMenuButton.canceled += instance.OnLeftControllerMenuButton;
            @LeftControllerTrigger.started += instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.performed += instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.canceled += instance.OnLeftControllerTrigger;
            @LeftControllerGrip.started += instance.OnLeftControllerGrip;
            @LeftControllerGrip.performed += instance.OnLeftControllerGrip;
            @LeftControllerGrip.canceled += instance.OnLeftControllerGrip;
            @LeftControllerStick.started += instance.OnLeftControllerStick;
            @LeftControllerStick.performed += instance.OnLeftControllerStick;
            @LeftControllerStick.canceled += instance.OnLeftControllerStick;
            @LeftControllerTrackingState.started += instance.OnLeftControllerTrackingState;
            @LeftControllerTrackingState.performed += instance.OnLeftControllerTrackingState;
            @LeftControllerTrackingState.canceled += instance.OnLeftControllerTrackingState;
            @LeftControllerGripButton.started += instance.OnLeftControllerGripButton;
            @LeftControllerGripButton.performed += instance.OnLeftControllerGripButton;
            @LeftControllerGripButton.canceled += instance.OnLeftControllerGripButton;
            @LeftControllerTriggerButton.started += instance.OnLeftControllerTriggerButton;
            @LeftControllerTriggerButton.performed += instance.OnLeftControllerTriggerButton;
            @LeftControllerTriggerButton.canceled += instance.OnLeftControllerTriggerButton;
            @RightControllerTrackingState.started += instance.OnRightControllerTrackingState;
            @RightControllerTrackingState.performed += instance.OnRightControllerTrackingState;
            @RightControllerTrackingState.canceled += instance.OnRightControllerTrackingState;
            @RightControllerStick.started += instance.OnRightControllerStick;
            @RightControllerStick.performed += instance.OnRightControllerStick;
            @RightControllerStick.canceled += instance.OnRightControllerStick;
            @RightControllerGrip.started += instance.OnRightControllerGrip;
            @RightControllerGrip.performed += instance.OnRightControllerGrip;
            @RightControllerGrip.canceled += instance.OnRightControllerGrip;
            @RightControllerTrigger.started += instance.OnRightControllerTrigger;
            @RightControllerTrigger.performed += instance.OnRightControllerTrigger;
            @RightControllerTrigger.canceled += instance.OnRightControllerTrigger;
            @RightControllerMenuButton.started += instance.OnRightControllerMenuButton;
            @RightControllerMenuButton.performed += instance.OnRightControllerMenuButton;
            @RightControllerMenuButton.canceled += instance.OnRightControllerMenuButton;
            @RightControllerSecondaryButton.started += instance.OnRightControllerSecondaryButton;
            @RightControllerSecondaryButton.performed += instance.OnRightControllerSecondaryButton;
            @RightControllerSecondaryButton.canceled += instance.OnRightControllerSecondaryButton;
            @RightControllerPrimaryButton.started += instance.OnRightControllerPrimaryButton;
            @RightControllerPrimaryButton.performed += instance.OnRightControllerPrimaryButton;
            @RightControllerPrimaryButton.canceled += instance.OnRightControllerPrimaryButton;
            @RightControllerRotation.started += instance.OnRightControllerRotation;
            @RightControllerRotation.performed += instance.OnRightControllerRotation;
            @RightControllerRotation.canceled += instance.OnRightControllerRotation;
            @RightControllerPosition.started += instance.OnRightControllerPosition;
            @RightControllerPosition.performed += instance.OnRightControllerPosition;
            @RightControllerPosition.canceled += instance.OnRightControllerPosition;
            @RightControllerGripButton.started += instance.OnRightControllerGripButton;
            @RightControllerGripButton.performed += instance.OnRightControllerGripButton;
            @RightControllerGripButton.canceled += instance.OnRightControllerGripButton;
            @RightControllerTriggerButton.started += instance.OnRightControllerTriggerButton;
            @RightControllerTriggerButton.performed += instance.OnRightControllerTriggerButton;
            @RightControllerTriggerButton.canceled += instance.OnRightControllerTriggerButton;
            @LeftControllerDeviceVelocity.started += instance.OnLeftControllerDeviceVelocity;
            @LeftControllerDeviceVelocity.performed += instance.OnLeftControllerDeviceVelocity;
            @LeftControllerDeviceVelocity.canceled += instance.OnLeftControllerDeviceVelocity;
            @RightControllerDeviceVelocity.started += instance.OnRightControllerDeviceVelocity;
            @RightControllerDeviceVelocity.performed += instance.OnRightControllerDeviceVelocity;
            @RightControllerDeviceVelocity.canceled += instance.OnRightControllerDeviceVelocity;
            @LeftControllerPrimary2DAxisClick.started += instance.OnLeftControllerPrimary2DAxisClick;
            @LeftControllerPrimary2DAxisClick.performed += instance.OnLeftControllerPrimary2DAxisClick;
            @LeftControllerPrimary2DAxisClick.canceled += instance.OnLeftControllerPrimary2DAxisClick;
            @RightControllerPrimary2DAxisClick.started += instance.OnRightControllerPrimary2DAxisClick;
            @RightControllerPrimary2DAxisClick.performed += instance.OnRightControllerPrimary2DAxisClick;
            @RightControllerPrimary2DAxisClick.canceled += instance.OnRightControllerPrimary2DAxisClick;
            @LeftControllerDeviceAngularVelocity.started += instance.OnLeftControllerDeviceAngularVelocity;
            @LeftControllerDeviceAngularVelocity.performed += instance.OnLeftControllerDeviceAngularVelocity;
            @LeftControllerDeviceAngularVelocity.canceled += instance.OnLeftControllerDeviceAngularVelocity;
            @RightControllerDeviceAngularVelocity.started += instance.OnRightControllerDeviceAngularVelocity;
            @RightControllerDeviceAngularVelocity.performed += instance.OnRightControllerDeviceAngularVelocity;
            @RightControllerDeviceAngularVelocity.canceled += instance.OnRightControllerDeviceAngularVelocity;
        }

        private void UnregisterCallbacks(ISVRControlActions instance)
        {
            @LeftControllerPosition.started -= instance.OnLeftControllerPosition;
            @LeftControllerPosition.performed -= instance.OnLeftControllerPosition;
            @LeftControllerPosition.canceled -= instance.OnLeftControllerPosition;
            @LeftControllerRotation.started -= instance.OnLeftControllerRotation;
            @LeftControllerRotation.performed -= instance.OnLeftControllerRotation;
            @LeftControllerRotation.canceled -= instance.OnLeftControllerRotation;
            @LeftControllerPrimaryButton.started -= instance.OnLeftControllerPrimaryButton;
            @LeftControllerPrimaryButton.performed -= instance.OnLeftControllerPrimaryButton;
            @LeftControllerPrimaryButton.canceled -= instance.OnLeftControllerPrimaryButton;
            @LeftControllerSecondaryButton.started -= instance.OnLeftControllerSecondaryButton;
            @LeftControllerSecondaryButton.performed -= instance.OnLeftControllerSecondaryButton;
            @LeftControllerSecondaryButton.canceled -= instance.OnLeftControllerSecondaryButton;
            @LeftControllerMenuButton.started -= instance.OnLeftControllerMenuButton;
            @LeftControllerMenuButton.performed -= instance.OnLeftControllerMenuButton;
            @LeftControllerMenuButton.canceled -= instance.OnLeftControllerMenuButton;
            @LeftControllerTrigger.started -= instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.performed -= instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.canceled -= instance.OnLeftControllerTrigger;
            @LeftControllerGrip.started -= instance.OnLeftControllerGrip;
            @LeftControllerGrip.performed -= instance.OnLeftControllerGrip;
            @LeftControllerGrip.canceled -= instance.OnLeftControllerGrip;
            @LeftControllerStick.started -= instance.OnLeftControllerStick;
            @LeftControllerStick.performed -= instance.OnLeftControllerStick;
            @LeftControllerStick.canceled -= instance.OnLeftControllerStick;
            @LeftControllerTrackingState.started -= instance.OnLeftControllerTrackingState;
            @LeftControllerTrackingState.performed -= instance.OnLeftControllerTrackingState;
            @LeftControllerTrackingState.canceled -= instance.OnLeftControllerTrackingState;
            @LeftControllerGripButton.started -= instance.OnLeftControllerGripButton;
            @LeftControllerGripButton.performed -= instance.OnLeftControllerGripButton;
            @LeftControllerGripButton.canceled -= instance.OnLeftControllerGripButton;
            @LeftControllerTriggerButton.started -= instance.OnLeftControllerTriggerButton;
            @LeftControllerTriggerButton.performed -= instance.OnLeftControllerTriggerButton;
            @LeftControllerTriggerButton.canceled -= instance.OnLeftControllerTriggerButton;
            @RightControllerTrackingState.started -= instance.OnRightControllerTrackingState;
            @RightControllerTrackingState.performed -= instance.OnRightControllerTrackingState;
            @RightControllerTrackingState.canceled -= instance.OnRightControllerTrackingState;
            @RightControllerStick.started -= instance.OnRightControllerStick;
            @RightControllerStick.performed -= instance.OnRightControllerStick;
            @RightControllerStick.canceled -= instance.OnRightControllerStick;
            @RightControllerGrip.started -= instance.OnRightControllerGrip;
            @RightControllerGrip.performed -= instance.OnRightControllerGrip;
            @RightControllerGrip.canceled -= instance.OnRightControllerGrip;
            @RightControllerTrigger.started -= instance.OnRightControllerTrigger;
            @RightControllerTrigger.performed -= instance.OnRightControllerTrigger;
            @RightControllerTrigger.canceled -= instance.OnRightControllerTrigger;
            @RightControllerMenuButton.started -= instance.OnRightControllerMenuButton;
            @RightControllerMenuButton.performed -= instance.OnRightControllerMenuButton;
            @RightControllerMenuButton.canceled -= instance.OnRightControllerMenuButton;
            @RightControllerSecondaryButton.started -= instance.OnRightControllerSecondaryButton;
            @RightControllerSecondaryButton.performed -= instance.OnRightControllerSecondaryButton;
            @RightControllerSecondaryButton.canceled -= instance.OnRightControllerSecondaryButton;
            @RightControllerPrimaryButton.started -= instance.OnRightControllerPrimaryButton;
            @RightControllerPrimaryButton.performed -= instance.OnRightControllerPrimaryButton;
            @RightControllerPrimaryButton.canceled -= instance.OnRightControllerPrimaryButton;
            @RightControllerRotation.started -= instance.OnRightControllerRotation;
            @RightControllerRotation.performed -= instance.OnRightControllerRotation;
            @RightControllerRotation.canceled -= instance.OnRightControllerRotation;
            @RightControllerPosition.started -= instance.OnRightControllerPosition;
            @RightControllerPosition.performed -= instance.OnRightControllerPosition;
            @RightControllerPosition.canceled -= instance.OnRightControllerPosition;
            @RightControllerGripButton.started -= instance.OnRightControllerGripButton;
            @RightControllerGripButton.performed -= instance.OnRightControllerGripButton;
            @RightControllerGripButton.canceled -= instance.OnRightControllerGripButton;
            @RightControllerTriggerButton.started -= instance.OnRightControllerTriggerButton;
            @RightControllerTriggerButton.performed -= instance.OnRightControllerTriggerButton;
            @RightControllerTriggerButton.canceled -= instance.OnRightControllerTriggerButton;
            @LeftControllerDeviceVelocity.started -= instance.OnLeftControllerDeviceVelocity;
            @LeftControllerDeviceVelocity.performed -= instance.OnLeftControllerDeviceVelocity;
            @LeftControllerDeviceVelocity.canceled -= instance.OnLeftControllerDeviceVelocity;
            @RightControllerDeviceVelocity.started -= instance.OnRightControllerDeviceVelocity;
            @RightControllerDeviceVelocity.performed -= instance.OnRightControllerDeviceVelocity;
            @RightControllerDeviceVelocity.canceled -= instance.OnRightControllerDeviceVelocity;
            @LeftControllerPrimary2DAxisClick.started -= instance.OnLeftControllerPrimary2DAxisClick;
            @LeftControllerPrimary2DAxisClick.performed -= instance.OnLeftControllerPrimary2DAxisClick;
            @LeftControllerPrimary2DAxisClick.canceled -= instance.OnLeftControllerPrimary2DAxisClick;
            @RightControllerPrimary2DAxisClick.started -= instance.OnRightControllerPrimary2DAxisClick;
            @RightControllerPrimary2DAxisClick.performed -= instance.OnRightControllerPrimary2DAxisClick;
            @RightControllerPrimary2DAxisClick.canceled -= instance.OnRightControllerPrimary2DAxisClick;
            @LeftControllerDeviceAngularVelocity.started -= instance.OnLeftControllerDeviceAngularVelocity;
            @LeftControllerDeviceAngularVelocity.performed -= instance.OnLeftControllerDeviceAngularVelocity;
            @LeftControllerDeviceAngularVelocity.canceled -= instance.OnLeftControllerDeviceAngularVelocity;
            @RightControllerDeviceAngularVelocity.started -= instance.OnRightControllerDeviceAngularVelocity;
            @RightControllerDeviceAngularVelocity.performed -= instance.OnRightControllerDeviceAngularVelocity;
            @RightControllerDeviceAngularVelocity.canceled -= instance.OnRightControllerDeviceAngularVelocity;
        }

        public void RemoveCallbacks(ISVRControlActions instance)
        {
            if (m_Wrapper.m_SVRControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISVRControlActions instance)
        {
            foreach (var item in m_Wrapper.m_SVRControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SVRControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SVRControlActions @SVRControl => new SVRControlActions(this);
    public interface ISVRControlActions
    {
        void OnLeftControllerPosition(InputAction.CallbackContext context);
        void OnLeftControllerRotation(InputAction.CallbackContext context);
        void OnLeftControllerPrimaryButton(InputAction.CallbackContext context);
        void OnLeftControllerSecondaryButton(InputAction.CallbackContext context);
        void OnLeftControllerMenuButton(InputAction.CallbackContext context);
        void OnLeftControllerTrigger(InputAction.CallbackContext context);
        void OnLeftControllerGrip(InputAction.CallbackContext context);
        void OnLeftControllerStick(InputAction.CallbackContext context);
        void OnLeftControllerTrackingState(InputAction.CallbackContext context);
        void OnLeftControllerGripButton(InputAction.CallbackContext context);
        void OnLeftControllerTriggerButton(InputAction.CallbackContext context);
        void OnRightControllerTrackingState(InputAction.CallbackContext context);
        void OnRightControllerStick(InputAction.CallbackContext context);
        void OnRightControllerGrip(InputAction.CallbackContext context);
        void OnRightControllerTrigger(InputAction.CallbackContext context);
        void OnRightControllerMenuButton(InputAction.CallbackContext context);
        void OnRightControllerSecondaryButton(InputAction.CallbackContext context);
        void OnRightControllerPrimaryButton(InputAction.CallbackContext context);
        void OnRightControllerRotation(InputAction.CallbackContext context);
        void OnRightControllerPosition(InputAction.CallbackContext context);
        void OnRightControllerGripButton(InputAction.CallbackContext context);
        void OnRightControllerTriggerButton(InputAction.CallbackContext context);
        void OnLeftControllerDeviceVelocity(InputAction.CallbackContext context);
        void OnRightControllerDeviceVelocity(InputAction.CallbackContext context);
        void OnLeftControllerPrimary2DAxisClick(InputAction.CallbackContext context);
        void OnRightControllerPrimary2DAxisClick(InputAction.CallbackContext context);
        void OnLeftControllerDeviceAngularVelocity(InputAction.CallbackContext context);
        void OnRightControllerDeviceAngularVelocity(InputAction.CallbackContext context);
    }
}
